### ISSUE TITLE
No .exe to install 

### ISSUE THREAD

**Issue by vitusq** [EliaSaSe/windows-update-remote-service#6]
Hi, 

I've downloaded and unzipped the file. As per the provided instruction, the **WcfWuRemoteService.exe** and **WcfWuRemoteClient.exe** needs to be executed. 
however, there seems to be no .EXE files in the zipped folder(s)

**Comment by EliaSaSe** [comment]
Hello vitusq, did you download the source code or ``WcfWuRemoteService.1.2.0.0.zip``? I downloaded the zip from the releases and I can find ``WcfWuRemoteService.1.2.0.0\WcfWuRemoteService.exe``. Maybe your anti virus detected that you downloaded the executable from the internet and deleted it?

**Comment by vitusq** [comment]
> Hello vitusq, did you download the source code or `WcfWuRemoteService.1.2.0.0.zip`? I downloaded the zip from the releases and I can find `WcfWuRemoteService.1.2.0.0\WcfWuRemoteService.exe`. Maybe your anti virus detected that you downloaded the executable from the internet and deleted it?

Hi EliaSaSe
Thank you for the quick response. 

I had to download the files separately under TAGS, so i have them now.
