### ISSUE TITLE
Unable to connect to remote hosts

### ISSUE THREAD

**Issue by vitusq** [EliaSaSe/windows-update-remote-service#7]
Hi EliaSaSe
 In **WcfWuRemoteService.exe.config**, i've altered the _createFirewallRule_ to "true" and saved it. 
Then I executed the **WcfWuRemoteService.exe** and after that executed **WcfWuRemoteClient.exe**

I added the remote host name as **net.tcp://<servername.FQDN>:8523/WuRemoteService** --> Clicked Add.
It starts to search for the remote host but fails with the error message in the image
<img width="431" alt="mRemoteNG_WPjaK0o6lN" src="https://user-images.githubusercontent.com/5568516/89827587-17230f00-db58-11ea-960b-f11449e8b9cb.png">

If i add **net.tcp://localhost:8523/WuRemoteService**, it gets added and works fine. But none of the remote host/servers which are added get added. They all get the error mentioned before.

Is there something which needs to be done? Am I doing something wrong here?

**Comment by vitusq** [comment]
Also FYI, I ran both the .exe with my Domain Admin account.

**Comment by EliaSaSe** [comment]
No, there should nothing more to do. In the Windows firewall, you should see a inbound rule. If not, the rule creation may failed. The log of the remote service may indicate that too.

On which interface did you bind the remote service? --> "Configure WcfWuRemoteService.exe.config, baseAddress"

I assume that the remote service is started on the target host. Does it work with the host IP address, just to verify there is no FQDN resolve problem?

**Comment by vitusq** [comment]
Initially i didn't make any changes to "Configure WcfWuRemoteService.exe.config, baseAddress" . So it was the default <add baseAddress="net.tcp://0.0.0.0:8523/WuRemoteService" />

However, i wasn't sure about it so i set it to the IP address of my Local machine (the one i was executing this from), but the error still persisted . Have i set it right ? or to which interface does it need to be set to ? 

I tried it with the IP address as well a few moments back, but the error is still the same.

a few questions about your last comments:
1. In the Windows firewall, you should see a inbound rule --> What would the name be exactly? 
2. The log of the remote service may indicate that too. --> Would you happen to know the Event ID number it generates? 
3. I assume that the remote service is started on the target host --> Could you please point me to the Service name?

I ask these just to be 100% sure i'm looking at the precise ones

**Comment by vitusq** [comment]
For some of the remote hosts, I've noticed this error as well which is different from the one I shared earlier.
![mRemoteNG_D0Npf7JsSg](https://user-images.githubusercontent.com/5568516/89882911-c6e39580-dbc7-11ea-9ced-acab0c6083f1.png)


I've been looking for the error in the event Viewer of the remote hosts, but don't seem to spot the need one you mentioned.

**Comment by EliaSaSe** [comment]
Ok, then the ``baseAddress`` of 0.0.0.0:8523 is fine, this binds to all interfaces on your system.

> ... the traget maschine actively refused it

This indicates, that the request is blocked by the network or the windows firewall.

In the windows firewall, the rule is named "Windows Update Remote Service". Look in the logfile of the remote service, not in the windows event log (default is ``log.txt``). If you set the log level to debug, you should see the following message in the log file, when the remote service starts:

> Debug: Authorizing application Windows Update Remote Service on the current firewall profile, image path for authorizing: <path to the executable>

If this fails, an exception after this line should be logged. ``Error: Could not create firewall rule.`` or so.

> Could you please point me to the Service name?

If you directly start ``WcfWuRemoteService.exe``, there is no windows service. I have understood, that you start both components (client & service) on the same machine, right? Or do you have trouble to connect, if the service runs on a different system?

**Comment by vitusq** [comment]
Hi EliaSaSe,

I've copied the unzipped folder "WcfWuRemoteService.1.2.0.0" to a shared path which is accessible to all the remote hosts.

Could you please assist with how the WcfWuRemoteService.exe is to be installed as a service onto multiple remote hosts?

Probably a lengthy but to be thought about a suggestion:
is it necessary to have it installed on the remote hosts in order for the Client to connect to it? why not it just be copied to the remote hosts Temp folder (as an example) and then have the Client run the **WcfWuRemoteService.exe** on a list of remote hosts provided to the Client & the location where it should look for the **WcfWuRemoteService.exe** to be residing in via a text file. If it exists, then it runs without any error and if not then the Client reports it.


Since in various Prod environments & servers installation of such a service won't be permitted (in my opinion)

**Comment by vitusq** [comment]
Just checking in if there's any update

**Comment by EliaSaSe** [comment]
> Could you please assist with how the WcfWuRemoteService.exe is to be installed as a service onto multiple remote hosts?

In the readme, you can find an example with the PowerShell command ``New-Service`` to do that. You can also use ``sc.exe`` to do the same. If you have many hosts, you may want to push the installation with your prefered automation/management solution (Ansible, Group Polices, PowerShell etc.) to the hosts.

> Is it necessary to have it installed on the remote hosts in order for the Client to connect to it

Yes, this is necessary. The clients talks to the service via network, the service talks to Windows Update locally.

> why not it just be copied to the remote hosts Temp folder (as an example) and then have the Client run the WcfWuRemoteService.exe [...]

I'm not sure if they understood your suggestion.

This does not work, because the service does not have any capabilities to speak with Windows Update Service via remote calls. The service must be executed locally on the target host. So you must ensure, that something starts WcfWuRemoteService.exe on the remote host. The client can't do that for you. For long term, a Windows service can handle this.

If you need a solution without any agent/service installed on the hosts, check out [install-windows-updates-remotely-with-the-powershell](https://4sysops.com/archives/install-windows-updates-remotely-with-the-powershell/) or [remotely-install-windows-updates](https://techthoughts.info/remotely-install-windows-updates/).

> Since in various Prod environments & servers installation of such a service won't be permitted

Yes, such services must be evaluated carefully before they should be installed in a prod environments.
